---
- name: install grafana
  yum:
    name: grafana

- name: configure grafana ini file
  template:
    src:
    dest:

- name: copy cloudwatch dashboard
  copy:
    src: '{{ item }}'
    dest: '{{ DASHBOAD_PATH }}'
    mode: 0755
  with_items: '{{ DASHBOARD_LIST }}'

- name: copy provisioning file for dashboard
  copy:
    src: cloudwatch-dashboard.yml
    dest: /etc/grafana/provisioning/dashboards/
    mode: 0640
  notify: start grafana

- name: copy provisioning file for datasource
  copy:
    src: cloudwatch-datasource.yml
    dest: /etc/grafana/provisioning/datasources/
    mode: 0640
  notify: start grafana
