---
- name: Download grafana
  get_url:
    url: '{{ GRAFANA_INSTALL_URL }}'
    dest: '{{ HOME_DIR }}' 

- name: install grafana
  yum:
    name: '{{ HOME_DIR }}/{{ GRAFANA_INSTALL_RPM }}'

- name: configure grafana ini file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: 0640

- name: copy cloudwatch dashboard
  copy:
    src: '{{ item }}'
    dest: '{{ DASHBOAD_PATH }}'
    mode: 0755
  with_items: '{{ DASHBOARD_LIST }}'

- name: copy provisioning file for dashboard
  copy:
    src: cloudwatch-dashboard.yml
    dest: /etc/grafana/provisioning/dashboards/
    mode: 0755
  notify: start grafana

- name: copy provisioning file for datasource
  copy:
    src: cloudwatch-datasource.yml
    dest: /etc/grafana/provisioning/datasources/
    mode: 0755
  notify: start grafana
